update ci/cd

diff --git a/.github/workflows/fins-build.yml b/.github/workflows/fins-build.yml
--- a/.github/workflows/fins-build.yml
+++ b/.github/workflows/fins-build.yml
@@ -2,9 +2,9 @@ name: FINS Plugin CI/CD
 
 on:
   push:
-    branches: [ "main", "master" ]
+    branches: [ "**" ]
   pull_request:
-    branches: [ "main", "master" ]
+    branches: [ "**" ]
 
 jobs:
   build:
@@ -33,6 +33,13 @@ jobs:
         uses: actions/checkout@v4
         with:
           submodules: recursive
+
+      - name: Check for package.yaml
+        run: |
+          if [ ! -f "package.yaml" ]; then
+            echo "Error: package.yaml not found. This repository might not be a valid FINS plugin. Exiting..."
+            exit 1
+          fi
 
       - name: Install Basic Tools
         run: |
